### ISSUE TITLE
Aximmetry Support

### ISSUE THREAD

**Issue by DuffyManCZ** [bitfocus/companion-module-aximmetry-composer#1]
Hey, we are using Aximmetry for our virtual studio set. We are now using companion to for controlling Aximmetry with OSC protocol, but that is not very comfortable. It would be really nice to have Aximmetry full support in Companion with feedbacks etc. Let me know, if I can help somehow to integrate Aximmetry into Companion! Thank you!

**Comment by daniep01** [comment]
@petefox Hi, have you been able to test the module?

**Comment by daniep01** [comment]
The module has been submitted for inclusion in the next Companion beta release.

**Comment by daniep01** [comment]
Released in Companion 3.1.0-6221
